eureka:
  instance:
    hostname: localhost
    port: 9000
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: prestador-servico
#          uri: http://localhost:8081
          uri: lb://PRESTADOR-SERVICO
          predicates:
            - Path=/ps/**
        - id: consumidor
#          uri: http://localhost:8082
          uri: lb://CONSUMIDOR
          predicates:
            - Path=/cons/**
